### ISSUE TITLE
Create a bootstrap to setup from fresh install

### ISSUE THREAD

**Issue by luanfrv0** [luanrvmood/dotfiles#1]
Would be nice to have an initial script that installs git and download this repository without a github ssh key associated.

## TODOS

- [x] add script to bootstrap git installation and download the repository
- [x] add script to generate ssh key and connect it to github account
- [x] link the downloaded repository with ssh associated
